//Obtener los productos
GET http://localhost:3000/api/productos


//Obtener productos por categoría
###
GET http://localhost:3000/api/productos/categorias/libros


//Obtener producto por ID
###
GET http://localhost:3000/api/productos/5


// Obtener productos por palabra
###
GET http://localhost:3000/api/productos/search/mochi



//Añadir productos nuevos
###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "titulo": "mochila",
    "precio": "10",
    "descripcion": "Mochila doble asa",
    "talla": "",
    "curso": "",
    "estado": "usado",
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRibNl9VvuLuA0LDwsWnqweoufc5Qry3hzQlP3LHmB_Ir_eDUPTbLksp0DknK4WTAGvO2fondw&usqp=CAc",
    "fk_usuario": 1,
    "fk_categoria": 2,
    "fk_colegio":3
}



//Modificar productos
###
PUT http://localhost:3000/api/productos/25
Content-Type: application/json

{
   "titulo": "Cambio para probar: mochila",
    "precio": "10",
    "descripcion": "Mochila doble asa",
    "talla": "",
    "curso": "",
    "estado": "usado",
    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRibNl9VvuLuA0LDwsWnqweoufc5Qry3hzQlP3LHmB_Ir_eDUPTbLksp0DknK4WTAGvO2fondw&usqp=CAc",
    "disponible": 0,
    "fk_usuario": 1,
    "fk_categoria": 2,
    "fk_colegio":3
}

//Borrar productos
###
DELETE http://localhost:3000/api/productos/25


// Obtener lista de pedidos por Id de usuario
###
GET http://localhost:3000/api/pedidos/2

// CREAR PEDIDOS
###
POST http://localhost:3000/api/pedidos
Content-Type: application/json

[
    {
      
        "fk_usuario": 2,
        "fk_articulo": 4
    },
    {
        "fk_usuario": 2,
        "fk_articulo": 5
    }
]


###
PUT  http://localhost:3000/api/productos/disponibilidad/8
Content-Type: application/json

{
    "disponible": 1
}

//PETICIONES DE USUARIOS
###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "nombre":"Jose",
    "apellidos": "Martinez",
    "email":"josemartinez@hotmail.com",
    "telefono": "654789321",
    "password":"123456",
    "fk_colegio": 3
}


//LOGIN DE USUARIO
###
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email":"josemartinez@hotmail.com",
    "password":"123456"
}


//OBTENER USUARIO POR ID
###
GET http://localhost:3000/api/usuarios/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoxMiwiY2FkdWNpZGFkIjoxNjIzOTE4MTkxLCJpYXQiOjE2MjM5MTcyOTF9.pHRP9pgiFNdO9QBha5G1O9cOGSX51lepxOYvLB3L3P8



//OBTENER PRODUCTOS SEGUN ID DE USUARIO
###
GET http://localhost:3000/api/productos/usuario/6



// ------> OBTENER COLEGIOS POR PAlABRA
###
GET http://localhost:3000/api/colegios/search/la m


// --> Articulos de cada cole
###
GET http://localhost:3000/api/colegios/articulos/purisima


// --> Nombre de coles e ID
###
GET http://localhost:3000/api/colegios/buscar


